core/urls.py
from django.urls import path
from .views import (
    CustomPasswordChangeView,
    CustomPasswordResetCompleteView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetDoneView,
    CustomPasswordResetView,
    ItemDetailView,
    HomeView,
    add_address,
    add_to_cart,
    check_approval_and_upload_key,
    delete_address,
    dsarcontrol_view,
    dsarrequest_view,
    edit_address,
    load_cities,
    login_view,
    logout_view,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    profile,
    second_verify,
    signup,
    test_form_view,
    test_signup,
    
)
from core import views

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug:slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('profile/', views.profile, name='profile'),
    path('add_address/', views.add_address, name='add_address'),
    path('edit_address/<int:address_id>/', views.edit_address, name='edit_address'),
    path('delete_address/<int:address_id>/', views.delete_address, name='delete_address'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('signup/', signup, name='signup'),
    path('dsar-module/', views.dsar_module, name='dsar_module'),
    path('verify-phone/', views.verify_phone, name='verify_phone'),
    path('second-verify/', second_verify, name='second_verify'),
    path('test-signup/', test_signup, name='test_signup'),
    path('test-form/', test_form_view, name='test_form_view'),
    path('login/', login_view, name='login'), 
    path('dsarrequest/', views.dsarrequest_view, name='dsarrequest'),
    path('dsarcontrol/', views.dsarcontrol_view, name='dsarcontrol'),
    path('dsarrequest/approve/<int:request_id>/', views.approve_dsarrequest, name='approve_dsarrequest'),
    path('check-dsar-status/', views.check_dsar_request_status, name='check_dsar_request_status'),
    path('dsarcontrol/approve/<int:request_id>/', views.approve_dsarcontrol, name='approve_dsarcontrol'),
    path('approve/<int:request_id>/', views.approve_dsarcontrol, name='approve_dsarcontrol'),
    path('upload_public_key/<int:request_id>/', views.upload_public_key, name='upload_public_key'),
    path('check-approval/<int:request_id>/', check_approval_and_upload_key, name='check_approval_and_upload_key'),
    path('inform/', views.inform, name='inform'),
    path('logout/', logout_view, name='logout_page'),

]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('auth/', include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser, Group, Permission


# Create your models here.
CATEGORY_CHOICES = (
    ('SB', 'Shirts And Blouses'),
    ('TS', 'T-Shirts'),
    ('SK', 'Skirts'),
    ('HS', 'Hoodies & Sweatshirts')
)

LABEL_CHOICES = (
    ('S', 'Sale'),
    ('N', 'New'),
    ('P', 'Promotion')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

class Country(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'core_country' 

class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'core_city'


class Slide(models.Model):
    caption1 = models.CharField(max_length=100)
    caption2 = models.CharField(max_length=100)
    link = models.CharField(max_length=100)
    image = models.ImageField(help_text="Size: 1920x570")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.caption1} - {self.caption2}"

class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:category", kwargs={'slug': self.slug})

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    stock_no = models.CharField(max_length=10)
    description_short = models.CharField(max_length=50)
    description_long = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={'slug': self.slug})

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey('BillingAddress', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey('BillingAddress', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = sum(order_item.get_final_price() for order_item in self.items.all())
        if self.coupon:
            total -= self.coupon.amount
        return total

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, default=1) 
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    zip_code = models.CharField(max_length=20)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES, default='B')
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'BillingAddresses'

class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_charge_id = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.user.username

    def clean(self):
        if not self.stripe_charge_id.isdigit():
            raise ValidationError('Stripe charge ID must contain only digits.')

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"




class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=255)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, default=1)  # Ensure this is set correctly
    state = models.CharField(max_length=100, blank=False)
    zip_code = models.CharField(max_length=10, blank=False)

    def __str__(self):
        return f'{self.street_address}, {self.city.name if self.city else "N/A"}, {self.state}, {self.zip_code}, {self.country.name if self.country else "N/A"}'


class DSARRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=15)
    request_time = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    approvedbydc = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    sms_sent = models.BooleanField(default=False)
    sms_sentt = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    

class PhoneVerification(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15)
    verification_code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)



class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = (
        ('user', 'User'),
        ('data_processor', 'Data Processor'),
        ('data_controller', 'Data Controller'),
    )
    public_key = models.TextField(blank=True, null=True)
    usertype = models.CharField(max_length=20, choices=USER_TYPE_CHOICES, default='user')
    groups = models.ManyToManyField(Group, related_name='customuser_set', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_set', blank=True)


    class Meta:
        db_table = 'core_customuser'
    
class CustomUserPermissions(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    permission = models.ForeignKey(Permission, on_delete=models.CASCADE)

class CustomUserGroups(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

templates/error.html
<!DOCTYPE html>
<html>
<head>
    <title>E-posta Gönderme Hatası</title>
</head>
<body>
    <h1>Bir hata oluştu:</h1>
    <p>{{ error }}</p>
</body>
</html>

templates/footer.html
{% load static %}
<!-- ------------------------------footer sub end---------------------------------- -->
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Abel|Lato|Open+Sans&display=swap" rel="stylesheet">
<style>
  
    /* footer */
#footer-main{
	background: #06212c;
	color: white;
	font-size: 0.8rem;
	padding: 2.5rem 0;
    font-family: 'Lato', sans-serif;
}

#footer-main a{
	font-size: 14px;
	display: block;
	margin: 0.3rem;
	color: grey;
}

#footer-main a:hover{
	font-weight: bold;
	color: white;
}

#footer-main h6 a{
    color: white;

    
}



#footer-main hr {
    margin-top: 1rem;
    margin-bottom: 1rem;
    border: 0;
    border-top: 1px solid white;
}

#footer-main img{
	margin-right: 0.6rem;
}
</style>

<footer id="footer-main">
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
            <br>

            <h6 class="mt-3"><a href="">FIND A STORE</a></h6>
            <h6 class="mt-3"><a href="{% url 'core:signup' %}">SIGN UP FOR EMAIL</a>
            <h6 class="mt-3"><a href="{% url 'core:signup' %}">BECOME A MEMBER</h6>
            
            <h6 class="mt-3"><a href="/admin/">ADMIN LOGIN</a></h6>
           
        </div>
        <div class="col-sm-3">
            <h6 class="mt-3"><a href="">GET HELP</a></h6>
            <a href="">Order Status</a>
            <a href="">Shipping and Delivery</a>
            <a href="">Returns</a>
            <a href="">Payment Options</a>
            <a href="">Contact Us</a>
        </div>
      
        </div>
      </div>
      <hr>
      
  </footer>
<!-- ------------------------------footer end---------------------------------- -->

templates/inform.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <div class="info-container">
        <h2>{% trans "How to Create a PGP Public Key" %}</h2>
        <p>{% trans "A PGP (Pretty Good Privacy) public key is used for encrypting data and ensuring its security. To create a PGP public key, follow these steps:" %}</p>

        <ol>
            <li>{% trans "Install a PGP tool on your computer. Popular tools include Gpg4win for Windows, GPG Suite for macOS, and GnuPG for Linux." %}</li>
            <li>{% trans "Open the PGP tool and look for an option to generate a new key pair." %}</li>
            <li>{% trans "Follow the prompts to create a new key pair. You will need to enter some personal information, such as your name and email address." %}</li>
            <li>{% trans "Set a strong passphrase to protect your private key. Make sure to remember this passphrase, as it will be required to use your private key." %}</li>
            <li>{% trans "Once the key pair is generated, you will have a public key and a private key. The public key is used to encrypt data, while the private key is used to decrypt it." %}</li>
            <li>{% trans "Export your public key from the PGP tool. This will be a file that you can upload or share with others." %}</li>
        </ol>

        <p>{% trans "For detailed instructions and screenshots, please refer to the documentation of the PGP tool you are using." %}</p>

        
        <a href="{% url 'core:upload_public_key' request_id=request.id %}">Upload Public Key</a>

    </div>

    <style>
        body {
            background-color: #4f92c5;
        }
        .info-container {
            max-width: 900px;
            margin: 50px auto;
            padding: 40px;
            background: #ffffff;
            border-radius: 12px;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            border: 1px solid #e0e0e0;
        }

        .info-container h2 {
            text-align: center;
            color: #333333;
            margin-bottom: 20px;
            font-size: 2.5em;
            font-weight: 700;
            border-bottom: 2px solid #007bff;
            padding-bottom: 10px;
        }

        .info-container p {
            font-size: 18px;
            color: #555555;
            line-height: 1.7;
            margin-bottom: 20px;
        }

        .info-container ol {
            margin: 20px 0;
            padding-left: 20px;
            font-size: 16px;
            color: #333333;
        }

        .info-container ol li {
            margin-bottom: 15px;
            position: relative;
            padding-left: 30px;
            line-height: 1.6;
        }

        .info-container ol li::before {
            content: '✔️';
            position: absolute;
            left: 0;
            top: 0;
            color: #28a745;
            font-size: 18px;
        }

        .info-container .back-link {
            display: block;
            text-align: center;
            margin-top: 30px;
            font-size: 18px;
            color: #007bff;
            text-decoration: none;
            font-weight: 500;
            padding: 10px;
            border: 2px solid #007bff;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }

        .info-container .back-link:hover {
            background-color: #007bff;
            color: #ffffff;
            text-decoration: none;
        }
    </style>
{% endblock content %}

templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background-color: white;
		color: black !important;
	}
	.topbar a:hover{
		color: black;
	}
	.nav-buttons {
        position: relative;
        display: inline-block;
    }
    .profile-options {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }
    .profile-options a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }
    .profile-options a:hover {
        background-color: #f1f1f1;
    }
    .show {
        display: block;
    }
</style>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			<div class="topbar">
				<span class="topbar-child1">
					Free shipping for standard order over $100
				</span>

				<div class="topbar-child2">
					
					<div class="topbar-language rs1-select2">
						<select class="selection-1" name="time">
							<option>USD</option>
							<option>EUR</option>
						</select>
					</div>
				</div>
			</div>

			<div class="wrap_header">
				<!-- Logo -->
				<a href="/" class="logo">
					<p style="color: black; "><b style="font-size: 22px;">D</b>SAR SHOP</p>
				</a>

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
							<li>
								<a href="/">Home</a>

							</li>

							<li>
								<a href="/shop/">Shop</a>
							</li>

							{% categories %}

							<li>
								<a href="{% url 'core:dsar_module' %}">DSAR Module</a>
							</li>
							
							{% if request.user.is_authenticated %}
							<li>
								<div class="header-wrapicon2">
								<a href="{% url 'core:order-summary' %}">
									
									<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>
									</a>
								</div>
							</li>
							
							<li>
								<div class="nav-buttons">
									<div class="left-nav" onclick="toggleProfileOptions()">
										<a href="#" id="profileLink">Profile</a>
										<div class="profile-options" id="profileOptions">
											<a href="{% url 'core:profile' %}">Account Information</a>
											<a href="{% url 'core:change_password' %}">Change Password</a>
											<a href="{% url 'core:logout_page' %}">Logout</a>
											
										</div>
									</div>
								</div>
							</li>
							<script>
								function toggleProfileOptions() {
									var profileOptions = document.getElementById("profileOptions");
									profileOptions.classList.toggle("show");
								}
							</script>
							
							<style>
								.profile-options {
									display: none;
									position: absolute;
									background-color: #f9f9f9;
									min-width: 160px;
									box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
									z-index: 1;
								}
							
								.profile-options a {
									color: black;
									padding: 12px 16px;
									text-decoration: none;
									display: block;
								}
							
								.profile-options a:hover {
									background-color: #f1f1f1;
								}
							
								.show {
									display: block;
								}
							</style>

							{% else %}
							<li>
								<a href="#">Login</a>
								<ul class="sub_menu">
									<li><a href="{% url 'core:login' %}">Login</a></li>
									<li><a href="{% url 'core:signup' %}">SignUp</a></li>
								</ul>
							</li>
							{% endif %}
						</ul>
					</nav>
				</div>

				
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="index.html" class="logo-mobile">
				<p style="color: black; "><b style="font-size: 22px;">D</b>SAR SHOP</p>
			</a>

			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					<a href="#" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide2"></span>

					<div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">0</span>

						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											White Shirt With Pleat Detail Back
										</a>

										<span class="header-cart-item-info">
											1 x $19.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Converse All Star Hi Black Canvas
										</a>

										<span class="header-cart-item-info">
											1 x $39.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Nixon Porter Leather Watch In Tan
										</a>

										<span class="header-cart-item-info">
											1 x $17.00
										</span>
									</div>
								</li>
							</ul>

							<div class="header-cart-total">
								Total: $75.00
							</div>

							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<span class="topbar-child1">
							Free shipping for standard order over $100
						</span>
					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								dsarmodule@gmail.com
							</span>

							<div class="topbar-language rs1-select2">
								<select class="selection-1" name="time">
									<option>USD</option>
									<option>EUR</option>
								</select>
							</div>
						</div>
					</li>

					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="/">Home</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">Shop</a>
					</li>

					{% categories_mobile %}

					{% if request.user.is_authenticated %}
					<li class="item-menu-mobile">
						<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
					</li>
					<li class="item-menu-mobile">
						<a href="{% url 'account_logout' %}">Logout</a>
					</li>
					{% else %}
					<li class="item-menu-mobile">
						<a href="#">Login</a>
						<ul class="sub-menu">
							<li><a href="{% url 'account_login' %}">Login</a></li>
							<li><a href="{% url 'account_signup' %}">SignUp</a></li>
						</ul>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>
					{% endif %}

				</ul>
			</nav>
		</div>
	</header>

templates/request_refund.html
{% extends 'base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-3 mt-3">
      <h2>Request Refund</h2>
      <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
     
    </div>
  </div>
</div>

{% endblock content %}